package org.telegram.utils;

public enum Countries {

    usa("USD"),
    israel("ILS"),
    United_Arab_Emirates("AED"),
    Afghanistan("AFN"),
    Albania("ALL"),
    Armenia("AMD"),
    Sint_Maarten(" ANG"),
    Angola("AOA"),
    Argentina("ARS"),
    Australia("AUD"),
    Aruba("AWG"),
    Azerbaijan("AZN"),
    Bosnia("BAM"),
    BBD("Barbados"),
    BDT("Barbados"),
    BGN("Barbados"),
    BHD("Barbados"),
    BIF("Barbados"),
    BMD("Barbados"),
    BND("Barbados"),
    BOB("Barbados"),
    BRL("Barbados"),
    BSD("Barbados"),
    BTN("Barbados"),
    BWP("Barbados"),
    BYN("Barbados"),
    BZD("Barbados"),
    canada("CAD"),
    CDF("Barbados"),
    CHF("Barbados"),
    CLP("Barbados"),
    CNY("Barbados"),
    COP("Barbados"),
    CRC("Barbados"),
    CUP("Barbados"),
    CVE("Barbados"),
    CZK("Barbados"),
    DJF("Barbados"),
    DKK("Barbados"),
    DOP("Barbados"),
    DZD("Barbados"),
    EGP("Barbados"),
    ERN("Barbados"),
    ETB("Barbados"),
    EUR("Barbados"),
    FJD("Barbados"),
    FKP("Barbados"),
    FOK("Barbados"),
    GBP("Barbados"),
    GEL("Barbados"),
    GGP("Barbados"),
    GHS("Barbados"),
    GIP("Barbados"),
    GMD("Barbados"),
    GNF("Barbados"),
    GTQ("Barbados"),
    GYD("Barbados"),
    HKD("Barbados");

    public final String extention;

    Countries(String extention) {
        this.extention = extention;
    }
}
