package org.telegram.utils;

public enum Countries {

    USA("inted state"),
    IL("israel"),
    AED("United Arab Emirates"),
    AFN("Afghanistan"),
    ALL("Albania"),
    AMD("Armenia"),
    ANG("Sint Maarten "),
    AOA("Angola"),
    ARS("Argentina"),
    AUD("Australia"),
    AWG("Aruba"),
    AZN("Azerbaijan"),
    BAM("Bosnia and Herzegovina"),
    BBD("Barbados"),
    BDT("Barbados"),
    BGN("Barbados"),
    BHD("Barbados"),
    BIF("Barbados"),
    BMD("Barbados"),
    BND("Barbados"),
    BOB("Barbados"),
    BRL("Barbados"),
    BSD("Barbados"),
    BTN("Barbados"),
    BWP("Barbados"),
    BYN("Barbados"),
    BZD("Barbados"),
    CAD("Barbados"),
    CDF("Barbados"),
    CHF("Barbados"),
    CLP("Barbados"),
    CNY("Barbados"),
    COP("Barbados"),
    CRC("Barbados"),
    CUP("Barbados"),
    CVE("Barbados"),
    CZK("Barbados"),
    DJF("Barbados"),
    DKK("Barbados"),
    DOP("Barbados"),
    DZD("Barbados"),
    EGP("Barbados"),
    ERN("Barbados"),
    ETB("Barbados"),
    EUR("Barbados"),
    FJD("Barbados"),
    FKP("Barbados"),
    FOK("Barbados"),
    GBP("Barbados"),
    GEL("Barbados"),
    GGP("Barbados"),
    GHS("Barbados"),
    GIP("Barbados"),
    GMD("Barbados"),
    GNF("Barbados"),
    GTQ("Barbados"),
    GYD("Barbados"),
    HKD("Barbados");

    public final String extention;

    Countries(String extention) {
        this.extention = extention;
    }
}
